---
resources:
  - name: spring-music-repo
    type: git
    source: 
      uri: https://github.com/mdolan-pivotal/spring-music

  - name: version
    type: semver
    source:
      driver: s3
      bucket: mdolan-pivotal-spring-music-artifacts
      key: current-version
      access_key_id: {{aws_access_key}}
      secret_key_id: {{aws_secret_key}}
      region_name: us-west-2
      initial_version: 1.0.0

jobs:
  - name: unit
    plan:
      - get: spring-music-repo
        trigger: true
      - task: unit
        file: spring-music-repo/ci/concourse/tasks/unit.yml
  - name: build-binary
    plan:
      - get: spring-music-repo
        trigger: true
        passed: [unit]
      - get: version
        params: {bump: minor}
      - task: build
        file: spring-music-repo/ci/concourse/tasks/build.yml
