---
resources:
  - name: spring-music-repo
    type: git
    source: 
      uri: https://github.com/mdolan-pivotal/spring-music.git

  - name: version
    type: semver
    source:
      bucket: spring-music-mdolan-repo
      key: current-version
      access_key_id: {{aws_access_key}}
      secret_access_key: {{aws_secret_key}}
      initial_version: 1.1.1

  - name: resource-deploy-web-app
    type: cf
    source:
      api: {{cf-api}}
      username: {{cf-username}}
      password: {{cf-password}}
      organization: {{cf-organization}}
      space: {{cf-space}}

jobs:
  - name: deploy-spring-music
    serial: true
    plan:
      - get: spring-music-repo
        trigger: true
      - task: unit-tests
        file: spring-music-repo/ci/concourse/tasks/unit.yml
      - put: version
        params: {bump: minor}
      - put: resource-deploy-web-app
        params:
          manifest:  spring-music-repo/manifest.yml
          path: spring-music-repo/build/libs/spring-music.war
